name: Sync Konado

env:
  SOURCE_GITHUB_REPO: godothub/konado
  TARGET_ATOMGIT_REPO: godothub/konado
  MAX_SYNC_FILES: 100
  START_RELEASE_TAG: ''
  SKIP_RELEASES_BEFORE_START: false
  SYNC_BRANCHES: true
  FORCE_SYNC_BRANCHES: true
  BRANCH_PUSH_BATCH_SIZE: 25
  GIT_HTTP_POST_BUFFER_BYTES: 524288000
  SYNC_TAGS: true
  FORCE_SYNC_TAGS: true
  SYNC_RELEASES: true

triggers:
  schedule: true
  schedule_cron:
    - '0 16 * * *'
  workflow_dispatch: true
